prepare_datasets:
  validation_split: .2
  image_size:
    - 180
    - 180
  batch_size: 32
  labels: inferred
  subset: both
  seed: 123

data_augmentation:
  random_flip_horizontal: True
  random_flip_vertical: False
  random_rotation: True
  random_zoom_height: True
  random_zoom_width: True
  random_brightness: True
  random_contrast: True
  random_translation_height: True
  random_translation_width: True

  random_rotation_factor: .2
  random_zoom_height_factor: .2
  random_zoom_width_factor: 0
  random_brightness_factor: .2
  random_contrast_lower_factor: .8
  random_contrast_upper_factor: 1.2
  random_translation_height_factor: .2
  random_translation_width_factor: .2

base_model:
  fine_tune_at: 100
  input_shape:
    - 180
    - 180
    - 3
  weights: imagenet
  include_top: False

callbacks:
  patience: 5
  factor: 0.1
  min_lr: 1e-6
